flyweight = "http://www.ufc.com/fighter/Weight_Class/Flyweight"
bantamweight = "http://www.ufc.com/fighter/Weight_Class/Bantamweight"
featherweight = "http://www.ufc.com/fighter/Weight_Class/Featherweight"
lightweight = "http://www.ufc.com/fighter/Weight_Class/Lightweight"
welterweight = "http://www.ufc.com/fighter/Weight_Class/Welterweight"
middleweight = "http://www.ufc.com/fighter/Weight_Class/Middleweight"
light_heavyweight = "http://www.ufc.com/fighter/Weight_Class/Light_Heavyweight"
heavyweight = "http://www.ufc.com/fighter/Weight_Class/Heavyweight"

the_ufc_link = "http://www.ufc.com/fighter/Weight_Class/filterFighters?offset=0&max=20&sort=lastName&order=asc&weightClass=&fighterFilter=Current"
